# Generated by Django 5.2.5 on 2025-12-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status2',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Started', 'Started'), ('Ended', 'Ended')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='bids',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='priority',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Started', 'Started'), ('Ended', 'Ended')], default='Draft', max_length=50),
        ),
    ]
