# Generated by Django 5.2.5 on 2025-12-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobs_status2_alter_bids_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='status2',
        ),
    ]
