# Generated by Django 5.2.5 on 2025-12-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_jobs_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
