# Generated by Django 5.2.5 on 2025-09-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userid',
            new_name='id',
        ),
    ]
