# Generated by Django 5.2.5 on 2025-12-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmusers', '0002_rename_userid_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='langitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
