# Generated by Django 5.2.5 on 2025-12-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmusers', '0003_users_langitude_users_latitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='langitude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('seeker', 'seeker'), ('provider', 'provider')], max_length=50),
        ),
    ]
